### ISSUE TITLE
react高阶组件-文本溢出打点

### ISSUE THREAD

**Issue by laoxiehhh** [laoxiehhh/laoxiea#18]
# react高阶组件-文本溢出打点
写这个组件的原因是，在实习的过程中，遇到的项目中有很多地方要进行文本展示，比如商品的信息展示、用户的评论，都需要用到溢出打点，所以将它抽离成一个高阶组件，可以在今后项目中遇到这类需求直接调用。

## 单行为本
如果文本为单行的话，进行溢出打点是比较容易实现的，只需3行css代码，且不用考虑浏览器兼容问题：
```css
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

## 多行文本
多行文本打点是比较麻烦的，因为要考虑到浏览器的兼容问题，并且多行文本在项目中遇到得比较频繁，所以这个react高阶组件主要是要能够兼容ie和火狐

### chrome或者现代移动端浏览器
其实文本溢出打点，在chrome或者现在的移动端浏览器上是很容易实现的，因为这些浏览器内核都支持
line-clamp这个属性，那么只需几行css代码就可以搞定：
```css
display: -webkit-box;
overflow: hidden;
text-overflow: ellipsis;
-webkit-box-orient: vertical;
-webkit-line-clamp: 2
```

### ie和火狐
因为公司要兼容ie9和火狐，而上面用到line-clamp属性在这些浏览器上是无法作用的，所以只能用其他的方式实现，考虑到用js来实现，但是js得去遍历每一行文本，来判断多少行，然后在规定的最后一行去操作dom来插 “...”, 这在页面文本较多的情况下，是非常耗费性能的一件事，而且操作dom，跟我们react的思想相违背，所以最后决定还是用css来解决，这样性能比较好。

我的思路是，在文本的直接父元素上添加样式，给其设一个before伪元素和一个after伪元素，before里的内容是 ‘...’ ,它通过绝对定位到文本块的右下角，然后after是一个背景色跟文本的背景色相同，它的位置是绝对定位到右边，这样当文本没有溢出时，after的位置就在before上，正好遮住 '...' ，当文本溢出时，after会被文本挤出到下面去，然后漏出 '...', 这样就做到了多行文本溢出打点：
```css
.block-with-text {
            overflow: hidden;
            position: relative;
            line-height: 1.2em;
            /* max-height = line-height (1.2) * (2) 设置三行行高 */
            max-height: 2.4em;
            text-align: justify;
            /*省略号到右边距的位置 */
            margin-right: 15px;
             /*给省略号的宽度留位置,三个点的宽度大概14px, 最好不要小于这个宽度*/
            padding-right: 15px;
        }
       /*创建省略号*/
        .block-with-text:before {
            content: '...';
            position: absolute;
            /* 省略号的显示位置定位在右下方*/
            right: 0;
            bottom: 0;
        }
       /*遮盖省略号*/
        .block-with-text:after {
            content: '';
            position: absolute;
            /*设置遮盖省略号的位置 */
            right: 0;
            /*设置遮盖省的大小 */
            width: 1em;
            height: 1em;
            margin-top: 0.2em;
            /*设置遮盖省略号的背景颜色，这个要和背景颜色一致 */
            background: white;
        }
```

## 封装成react高阶组件
确定好思路后，就按照之前的思路，封装成一个react高阶组件，但是因为考虑到上面多行文本的兼容时方案，其实我们的高阶组件是有一定要求的，就是如果要兼容ie9或者火狐，我们传给这个高阶组件的文本组件应该只被一层块级父元素包裹。因为我们在高阶组件中，是有个逻辑是要找到传进来的文本组件的直接块级父元素，所以这是这个高阶组件还需要优化的地方。
下面直接看代码：
```js
import React, { Component } from 'react' 
import jss from 'jss'
import preset from 'jss-preset-default'
import classlist from 'classlist'


jss.setup(preset())

// 只有一行的文本，溢出打点的样式
const ellipsisStyle = {
  wrapper: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap'
  }
}

// 支持line-clamp的多行文本溢出打点的样式
const clampStyle = {
  display: '-webkit-box',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  WebkitBoxOrient: 'vertical'
}
const getClampStyle = (lines = 2) => {
  return {
    ...clampStyle,
    WebkitLineClamp: +lines
  }
}

const getFallbackClampStyle = ({ lines, width, lineHeight, bgColor }) => {
  let w = typeof width === 'number' ? `${width}px` : '100%'
  let h = `${lineHeight}em`
  return {
    wrapper: {
      boxSizing: "border-box",
      overflow: "hidden",
      position: "relative",
      lineHeight: h,
      /* max-height = line-height (1.2) * (2) 设置三行行高 */
      maxHeight: `${lineHeight * lines}em`,
      width: w,
      textAlign: "justify",
       /*给省略号的宽度留位置,三个点的宽度大概14px, 最好不要小于这个宽度*/
      paddingRight: `0.9em`,
      '&:before': {
        content: '"..."',
        position: "absolute",
        /* 省略号的显示位置定位在右下方*/
        right: 0,
        bottom: 0,
      },
      '&:after': {
        content: '""',
        position: "absolute",
        /*设置遮盖省略号的位置 */
        right: 0,
        /*设置遮盖省的大小 */
        width: "1em",
        height: "1em",
        marginTop: "0.2em",
        /*设置遮盖省略号的背景颜色，这个要和背景颜色一致 */
        background: `${bgColor}`,
      }
    }
  }
}
// 是否支持line-clamp样式
const isLineClampSupported = () => {
  if (typeof window !== 'undefined' && document) {
    // 在root元素上标识是否支持line-clamp样式，避免每次获取是否支持
    let root = document.querySelector('html')
    let cl = classlist(root)
    if (cl.contains(LINE_CLAMP_FLAG_CLS)) {
      return true
    } else {
      let div = document.createElement('div')
      let supported = 'webkitLineClamp' in div.style
      supported && cl.add(LINE_CLAMP_FLAG_CLS)
      return supported
    }
  }
  return false
}

// 标识是否支持line-clamp样式的类名
const LINE_CLAMP_FLAG_CLS = 'webkit-line-clamp'

/**
 * 实现超出{lines}行之后文本末尾展示省略号功能的高阶组件
 * @param clsName         不传时，判断样式支持后用行内样式实现，不支持时用fallback样式替代
 * @param lines           不传时，默认2行
 * @param width           文本宽度，可不指定
 * @param lineHeight      文本高度，必填项,单位是em,传参时不用带单位
 * @param bgColor         文本的背景颜色，就是原组件的文本的背景颜色
 * 如果支持line-clamp样式，则只需要传lines参数，其他的样式可以自己在组件上设置
 */

const lineClamp = ({ clsName, lines = 2, width, lineHeight, bgColor }) => WrappedComponent => {
  return class NewComponent extends Component {
    componentDidMount () {
      if (this.wrapper) {
        let styleSheetObj
        if (lines <= 1) {
          styleSheetObj = ellipsisStyle
        } else if (!isLineClampSupported()) {
          styleSheetObj = getFallbackClampStyle({
            lines,
            width,
            lineHeight,
            bgColor
          })
        } else {
          return 
        }
        try {
          const { classes } = jss.createStyleSheet(styleSheetObj).attach()
          let cl = classlist(this.wrapper.children[0])
          cl.add(classes.wrapper)
        } catch (e) {
          console.log(e)
        }
      }
    }

    getclsName () {
      let className = null
      if (clsName) {
        // 传了clsName，用clsName的样式
        className = clsName
      }
      return lines <= 1 ? '' : className
    }

    getStyle () {
      let style = null
      if (!clsName) {
        // 没传clsName，用行内样式
        style = getClampStyle(lines)
      }
      return lines <= 1 ? {} : style
    }

    render () {
      let { children, ...rest } = this.props
      let wrappedComponent = (
        <WrappedComponent {...rest}>
          {children}
        </WrappedComponent>
      )
      if (!wrappedComponent) {
        return null
      }
      if (isLineClampSupported()) {
        return (
          <div
            className={this.getclsName()}
            style={this.getStyle()}
            ref={node => {
              this.wrapper = node
            }}
          >
            {wrappedComponent}
          </div>
        )
      } else {
        return (
          <div ref={node => this.wrapper = node}>
            <WrappedComponent {...rest}>
              {children}
            </WrappedComponent>
          </div>
        )
      }
    }
  }
}

export default lineClamp
```
